---

- hosts: all
  become: true
  vars_files:
    - vars/wordpress.yml

  roles:
    - nginx
    - mysql
    - php
    - wordpress

  post_tasks:
  - name: restart php
    systemd:
      name: php7.4-fpm
      state: restarted
      enabled: true

  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
      enabled: true
